name: "CI (Atualização REACT Producao 3015): GitAction"
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    # Ativa esse fluxo de trabalho para cada push que acontecer apontando para a branch main
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

    workflow_dispatch:

jobs:
    producao3015: 
      runs-on: ubuntu-latest
      steps:
            - uses: actions/checkout@v3
            
            # Runs a single command using the runners shell
            - name: Run a one-line script
              run: echo Hello, world!
    
    deploy-producao3015:
      runs-on: ubuntu-latest
      environment:
              name: producao3015
      needs: producao3015
      steps:
            - name: Repo Checkout
              uses: actions/checkout@v3
            - name: producao3015 Deployment
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.KEY_SECRETORIGINAL}}
                #ARGS: "-rlgoDzvc --delete"
                SOURCE: "./"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}

